controller_manager:
  ros__parameters:
    update_rate: 100 
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

drive_controller:
  ros__parameters:
    reference_timeout: 1.0 
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    kinematics:
        base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
        wheels_radius: 0.3
        sum_of_robot_center_projection_on_X_Y_axis: 1.1
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
